### ISSUE TITLE
Staging/Production workflows not working

### ISSUE THREAD

**Issue by yuliankarapetkov** [supabase/supabase-action-example#36]
# Bug report

## Describe the bug

Staging/Production workflows are failing

## To Reproduce

Set up the the workflows and push to the corresponding repos. 

## Expected behavior

Workflows run and migrations are deployed successfully. 

## Actual behavior

Workflow fails and migrations are not deployed.

## Screenshots

<img width="1078" alt="image" src="https://github.com/supabase/supabase-action-example/assets/6671521/f843747e-ff4d-4b01-906a-f95ef52b4e68">

**Comment by sweatybridge** [comment]
I believe this is fixed in the latest cli release. Could you rerun and try again?

**Comment by yuliankarapetkov** [comment]
@sweatybridge I'm already using the latest CLI:

```
- name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
```
