### ISSUE TITLE
Should we push config.toml too?

### ISSUE THREAD

**Issue by tadeegan** [supabase/supabase-action-example#42]
# Improve documentation

A large amount of supabase functionallity is controlled by config.toml. If we want to manage a staging enviornment that mirrors the prod one, how can we push the config.toml with correct envs? Should we use `supabase config push` in ci?

So far I tried something like:

```
name: Deploy Migrations to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: xxx
      DEPLOY_URL: staging.xxx.co

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
      - run: supabase config push
```
